### ISSUE TITLE
Trying to install WinUSB on Riffmaster: System.InvalidOperationException: Mapping mode is not set! Cannot create mapper.

### ISSUE THREAD

**Issue by kshoichi** [TheNathannator/RB4InstrumentMapper#17]
RB4 found the Riffmaster, but when I clicked "Switch Driver" I received this error message. Now RB4 crashes whenever I try to run it and the Riffmaster is connected.

Log: 
[2024/05/05 07:10:42] EXCEPTION
------------------------------
Failed to switch device USB\VID_0E6F&PID_0248\0000834C85BAD2CC to WinUSB!
Nefarius.Utilities.DeviceManagement.Exceptions.Win32Exception: NULL-driver installation failed
   at Nefarius.Utilities.DeviceManagement.PnP.PnPDevice.InstallNullDriver(Boolean& rebootRequired)
   at RB4InstrumentMapper.Parsing.WinUsbBackend.SwitchDeviceToWinUSB(UsbPnPDevice device)
------------------------------
[2024/05/05 07:10:46] -------------------
[2024/05/05 07:10:46] UNHANDLED EXCEPTION
[2024/05/05 07:10:46] -------------------
[2024/05/05 07:10:46] EXCEPTION
------------------------------
Unhandled exception!
System.InvalidOperationException: Mapping mode is not set! Cannot create mapper.
   at RB4InstrumentMapper.Parsing.MapperFactory.GetMapper(XboxClient client, CreateMapper createVigem, CreateMapper createVjoy)
   at RB4InstrumentMapper.Parsing.XboxClient.HandleMessage(XboxCommandHeader header, ReadOnlySpan`1 commandData)
   at RB4InstrumentMapper.Parsing.XboxDevice.HandlePacket(XboxPacket packet)
   at RB4InstrumentMapper.Parsing.XboxWinUsbDevice.ReadThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
------------------------------

**Comment by TheNathannator** [comment]
This issue should be fixed as of v4.2.0 pre-release 1, give the latest pre-release a go and see if that works for you.

**Comment by TheNathannator** [comment]
Closing this issue due to inactivity, please re-open if it still happens to you.
