### ISSUE TITLE
vigemclient.dll not found

### ISSUE THREAD

**Issue by BigBrawler** [TheNathannator/RB4InstrumentMapper#36]
VigEmBus is installed. I have tried multiple versions.

`[2024/09/03 17:00:50] -------------------
[2024/09/03 17:00:50] UNHANDLED EXCEPTION
[2024/09/03 17:00:50] -------------------
[2024/09/03 17:00:50] EXCEPTION
------------------------------
Unhandled exception!
System.DllNotFoundException: Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.ViGEmClient.vigem_disconnect(IntPtr vigem)
   at Nefarius.ViGEm.Client.ViGEmClient.ReleaseUnmanagedResources() in E:\Programming\Source\forks\ViGEm.NET\ViGEmClient\ViGEmClient.cs:line 41
   at Nefarius.ViGEm.Client.ViGEmClient.Finalize() in E:\Programming\Source\forks\ViGEm.NET\ViGEmClient\ViGEmClient.cs:line 48
------------------------------
`

**Comment by OMGMYSPLEEN80** [comment]
I'm in the same boat.  Tried reinstalling everything a few times with no luck.

**Comment by BigBrawler** [comment]
I fixed this error on mine. Reinstall VigemBus a few times before reinstalling this a few times. Go really slow and let it finish every time. Make sure you reboot after.

**Comment by snorkrat** [comment]
I was having this issue and the solution for me was to install [Visual Studio 2019 from here](https://visualstudio.microsoft.com/vs/older-downloads/).

**Comment by lolelijah** [comment]
I'm also having this issue. I've tried reinstalling VigemBus several times, including uninstalling and using older versions. I've also tried reinstalling RB4IM several times and rebooting between installs. This error occurs and also an error "No controller emulators found". This is my first time installing RB4IM on my computer and have never gotten it to open without getting these two errors.

**Comment by BigBrawler** [comment]
Go get the latest vcruntimes. I used techpowerup's [all-in-one visual c runtime](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)

Reboot after installing them. Then check for Windows updates in Settings.
